'use strict';

const SOURCES = [
  {
    id: 'sys_log',
    label: 'System log',
    description: 'Auth, alarms, hardware events, errors, maintenance notes',
    dateField: 'at',
    defaultColumns: ['at', 'level', 'category', 'message', 'user.name'],
    fields: [
      { id: 'at', label: 'Time', type: 'datetime' },
      { id: 'level', label: 'Level', type: 'string' },
      { id: 'category', label: 'Category', type: 'string' },
      { id: 'message', label: 'Message', type: 'string' },
      { id: 'user.name', label: 'User name', type: 'string' },
      { id: 'user.email', label: 'User email', type: 'string' },
      { id: 'user.role', label: 'User role', type: 'string' },
      { id: 'detail', label: 'Detail', type: 'json' },
      { id: 'host', label: 'Host', type: 'string' },
    ],
    filters: [
      { id: 'level', label: 'Level', type: 'enum', options: ['error', 'warn', 'info', 'maintenance'] },
      { id: 'category', label: 'Category', type: 'string', placeholder: 'e.g. alarms, mqtt' },
      { id: 'userId', label: 'User id', type: 'string' },
    ],
  },
  {
    id: 'hardware_assignments',
    label: 'Hardware history',
    description: 'Device commission and swap records by position',
    dateField: 'installedAt',
    defaultColumns: ['installedAt', 'positionId', 'serialNumber', 'vendor', 'model', 'swapType', 'note'],
    fields: [
      { id: 'installedAt', label: 'Installed', type: 'datetime' },
      { id: 'removedAt', label: 'Removed', type: 'datetime' },
      { id: 'positionId', label: 'Position', type: 'string' },
      { id: 'positionName', label: 'Position name', type: 'string' },
      { id: 'deviceId', label: 'Device id', type: 'string' },
      { id: 'serialNumber', label: 'Serial', type: 'string' },
      { id: 'vendor', label: 'Vendor', type: 'string' },
      { id: 'model', label: 'Model', type: 'string' },
      { id: 'platform', label: 'Platform', type: 'string' },
      { id: 'driverType', label: 'Driver', type: 'string' },
      { id: 'swapType', label: 'Swap type', type: 'string' },
      { id: 'note', label: 'Note', type: 'string' },
    ],
    filters: [
      { id: 'positionId', label: 'Position id', type: 'string' },
      { id: 'serialNumber', label: 'Serial', type: 'string' },
    ],
  },
  {
    id: 'tag_samples',
    label: 'Tag historian samples',
    description: 'Archived SCADA pen samples from MongoDB time series',
    dateField: 'timestamp',
    defaultColumns: ['timestamp', 'tagId', 'value', 'scaledValue', 'running', 'projectName'],
    fields: [
      { id: 'timestamp', label: 'Time', type: 'datetime' },
      { id: 'tagId', label: 'Tag', type: 'string' },
      { id: 'tagType', label: 'Type', type: 'string' },
      { id: 'value', label: 'Value', type: 'number' },
      { id: 'scaledValue', label: 'Scaled', type: 'number' },
      { id: 'running', label: 'Running', type: 'boolean' },
      { id: 'projectName', label: 'Project', type: 'string' },
      { id: 'source', label: 'Source', type: 'string' },
    ],
    filters: [
      { id: 'tagId', label: 'Tag id', type: 'string' },
      { id: 'projectName', label: 'Project', type: 'string' },
    ],
  },
  {
    id: 'roi_summary',
    label: 'ROI calculator (saved assets)',
    description: 'Payback and ROI summary from settings.json (leak detection, pool, combined)',
    dateField: 'asset',
    defaultColumns: ['asset', 'upfrontCost', 'annualGrossSavings', 'netAnnualBenefit', 'paybackMonths', 'roiPercent'],
    fields: [
      { id: 'asset', label: 'Asset', type: 'string' },
      { id: 'upfrontCost', label: 'Upfront cost', type: 'number' },
      { id: 'annualGrossSavings', label: 'Annual gross savings', type: 'number' },
      { id: 'amortizedAnnualCost', label: 'Amortized annual cost', type: 'number' },
      { id: 'netAnnualBenefit', label: 'Net annual benefit', type: 'number' },
      { id: 'paybackMonths', label: 'Payback (months)', type: 'number' },
      { id: 'roiPercent', label: 'ROI %', type: 'number' },
    ],
    filters: [],
  },
  {
    id: 'cmms_work_orders',
    label: 'CMMS work orders',
    description: 'Work orders from the local CMMS store (open, in progress, completed)',
    dateField: 'createdAt',
    defaultColumns: ['number', 'title', 'status', 'priority', 'assetId', 'assignee', 'dueAt', 'overdue', 'source'],
    fields: [
      { id: 'number', label: 'WO #', type: 'string' },
      { id: 'title', label: 'Title', type: 'string' },
      { id: 'description', label: 'Description', type: 'string' },
      { id: 'status', label: 'Status', type: 'string' },
      { id: 'priority', label: 'Priority', type: 'string' },
      { id: 'assetId', label: 'Asset', type: 'string' },
      { id: 'assignee', label: 'Assignee', type: 'string' },
      { id: 'source', label: 'Source', type: 'string' },
      { id: 'sourceRef', label: 'Source ref', type: 'string' },
      { id: 'createdAt', label: 'Created', type: 'datetime' },
      { id: 'updatedAt', label: 'Updated', type: 'datetime' },
      { id: 'dueAt', label: 'Due', type: 'datetime' },
      { id: 'completedAt', label: 'Completed', type: 'datetime' },
      { id: 'overdue', label: 'Overdue', type: 'string' },
    ],
    filters: [
      { id: 'status', label: 'Status', type: 'enum', options: ['open', 'in_progress', 'complete', 'cancelled', 'open,in_progress'] },
      { id: 'priority', label: 'Priority', type: 'enum', options: ['low', 'normal', 'high', 'urgent'] },
      { id: 'source', label: 'Source', type: 'enum', options: ['manual', 'alarm', 'pm', 'pdm'] },
      { id: 'overdue', label: 'Overdue only', type: 'enum', options: ['yes'] },
      { id: 'assetId', label: 'Asset id', type: 'string', placeholder: 'pump-101' },
    ],
  },
  {
    id: 'cmms_pm_schedules',
    label: 'CMMS PM schedules',
    description: 'Preventive maintenance schedules and due dates',
    dateField: 'nextDueAt',
    defaultColumns: ['title', 'assetId', 'intervalDays', 'nextDueAt', 'lastCompletedAt', 'overdue', 'assignee', 'enabled'],
    fields: [
      { id: 'title', label: 'Title', type: 'string' },
      { id: 'assetId', label: 'Asset', type: 'string' },
      { id: 'intervalDays', label: 'Interval (days)', type: 'number' },
      { id: 'nextDueAt', label: 'Next due', type: 'datetime' },
      { id: 'lastCompletedAt', label: 'Last completed', type: 'datetime' },
      { id: 'assignee', label: 'Assignee', type: 'string' },
      { id: 'enabled', label: 'Enabled', type: 'boolean' },
      { id: 'overdue', label: 'Overdue', type: 'string' },
      { id: 'daysUntilDue', label: 'Days until due', type: 'number' },
      { id: 'createdAt', label: 'Created', type: 'datetime' },
    ],
    filters: [
      { id: 'overdue', label: 'Overdue only', type: 'enum', options: ['yes'] },
      { id: 'enabled', label: 'Enabled', type: 'enum', options: ['yes', 'no'] },
      { id: 'assetId', label: 'Asset id', type: 'string', placeholder: 'pump-101' },
    ],
  },
  {
    id: 'collection',
    label: 'MongoDB collection',
    description: 'Query an allowlisted MongoDB collection with custom columns',
    dateField: 'at',
    defaultColumns: [],
    fields: [],
    filters: [],
    collections: [
      'sys_log',
      'tag_samples_ts',
      'tag_logs',
      'hardware_assignments',
      'edge_inference_ts',
      'pdm_features',
      'camera_events',
    ],
  },
];

const TEMPLATES = [
  {
    id: 'alarm_acks',
    name: 'Alarm acknowledgements',
    sourceId: 'sys_log',
    filter: { category: 'alarms' },
    columns: ['at', 'level', 'category', 'message', 'user.name'],
    title: 'Alarm acknowledgements',
  },
  {
    id: 'hardware_swaps',
    name: 'Hardware change-outs',
    sourceId: 'hardware_assignments',
    columns: ['installedAt', 'positionId', 'serialNumber', 'vendor', 'model', 'swapType', 'note'],
    title: 'Hardware change-outs',
  },
  {
    id: 'errors',
    name: 'System errors',
    sourceId: 'sys_log',
    filter: { level: 'error' },
    columns: ['at', 'category', 'message', 'user.name'],
    title: 'System errors',
  },
  {
    id: 'mqtt_auth_failures',
    name: 'MQTT auth failures',
    sourceId: 'sys_log',
    filter: { category: 'mqtt', level: 'warn' },
    columns: ['at', 'level', 'message', 'detail'],
    title: 'MQTT broker auth failures',
  },
  {
    id: 'mqtt_device_events',
    name: 'MQTT device connect/disconnect',
    sourceId: 'sys_log',
    filter: { category: 'mqtt' },
    columns: ['at', 'level', 'message', 'detail'],
    title: 'MQTT broker device events',
  },
  {
    id: 'roi_assets',
    name: 'ROI calculator (assets)',
    sourceId: 'roi_summary',
    columns: ['asset', 'upfrontCost', 'annualGrossSavings', 'amortizedAnnualCost', 'netAnnualBenefit', 'paybackMonths', 'roiPercent'],
    title: 'ROI calculator summary',
    openRoiPanel: true,
  },
  {
    id: 'open_work_orders',
    name: 'Open work orders',
    sourceId: 'cmms_work_orders',
    filter: { status: 'open,in_progress' },
    columns: ['number', 'title', 'status', 'priority', 'assetId', 'assignee', 'dueAt', 'overdue', 'source'],
    title: 'Open work orders',
    openCmmsPanel: true,
  },
  {
    id: 'overdue_pm',
    name: 'Overdue PM schedules',
    sourceId: 'cmms_pm_schedules',
    filter: { overdue: 'yes' },
    columns: ['title', 'assetId', 'intervalDays', 'nextDueAt', 'lastCompletedAt', 'overdue', 'assignee'],
    title: 'Overdue PM schedules',
    openCmmsPanel: true,
  },
  {
    id: 'pdm_pending_pm',
    name: 'PdM proactive PM work orders',
    sourceId: 'cmms_work_orders',
    filter: { source: 'pdm', status: 'open,in_progress' },
    columns: ['number', 'title', 'priority', 'assetId', 'dueAt', 'overdue', 'assignee', 'createdAt'],
    title: 'PdM pending-failure PM work orders',
    openCmmsPanel: true,
  },
  {
    id: 'pdm_feature_health',
    name: 'PdM feature health (MongoDB)',
    sourceId: 'collection',
    collection: 'pdm_features',
    filter: {},
    columns: ['timestamp', 'assetId', 'healthIndex', 'edgeScore', 'runAmpsAvg', 'startsDelta'],
    title: 'PdM feature windows',
  },
  {
    id: 'completed_work_orders',
    name: 'Completed work orders',
    sourceId: 'cmms_work_orders',
    filter: { status: 'complete' },
    columns: ['number', 'title', 'assetId', 'assignee', 'completedAt', 'source', 'createdAt'],
    title: 'Completed work orders',
    openCmmsPanel: true,
  },
];

function getSource(sourceId) {
  return SOURCES.find((s) => s.id === sourceId) || null;
}

function listCatalog() {
  return {
    sources: SOURCES.map((s) => ({
      id: s.id,
      label: s.label,
      description: s.description,
      dateField: s.dateField,
      defaultColumns: s.defaultColumns,
      fields: s.fields,
      filters: s.filters,
      collections: s.collections || null,
    })),
    templates: TEMPLATES,
  };
}

module.exports = {
  SOURCES,
  TEMPLATES,
  getSource,
  listCatalog,
};
