#!/usr/bin/env bash
set -euo pipefail

cat > /etc/mosquitto/conf.d/peaklogic.conf <<'EOF'
# Generated by install-mqtt-droplet.sh
allow_anonymous false
password_file /etc/mosquitto/passwd

listener 1883

listener 8883
cafile /etc/mosquitto/certs/server.crt
certfile /etc/mosquitto/certs/server.crt
keyfile /etc/mosquitto/certs/server.key
require_certificate false
EOF

chmod 0700 /etc/mosquitto/passwd
systemctl reset-failed mosquitto
systemctl restart mosquitto
sleep 1
systemctl is-active mosquitto
ss -lnt | grep -E ':1883|:8883' || true

set -a
# shellcheck disable=SC1091
. /etc/peaklogic/mqtt.env
set +a

mosquitto_pub -h 127.0.0.1 -p 1883 -u "$MOSQUITTO_USER" -P "$MOSQUITTO_PASS" -t test/ping -m ok && echo PLAIN_OK
mosquitto_pub -h 127.0.0.1 -p 8883 --insecure -u "$MOSQUITTO_USER" -P "$MOSQUITTO_PASS" -t test/ping -m ok-tls && echo TLS_OK
