#!/usr/bin/env bash
# Phase 1 — dedicated Mosquitto droplet (no Node SaaS).
# Run as root on peaklogic-mqtt after copying deploy/cloud helpers + mqtt.env.
#
#   sudo bash deploy/cloud/phase1/install-mqtt-droplet.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEBIAN_DIR="$(cd "$SCRIPT_DIR/../debian" && pwd)"
MQTT_ENV="${PEAKLOGIC_MQTT_ENV:-/etc/peaklogic/mqtt.env}"

log() { printf '[peaklogic-mqtt] %s\n' "$*"; }
die() { printf '[peaklogic-mqtt] ERROR: %s\n' "$*" >&2; exit 1; }

[[ "${EUID:-$(id -u)}" -eq 0 ]] || die "Run as root"

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq mosquitto mosquitto-clients openssl ca-certificates

install -d -m 0750 /etc/peaklogic
if [[ ! -f "$MQTT_ENV" ]]; then
  install -m 0640 "$SCRIPT_DIR/.env.mqtt.example" "$MQTT_ENV"
  die "Created $MQTT_ENV — set MOSQUITTO_PASS (and domain), then re-run"
fi

# shellcheck disable=SC1090
set -a
# strip CR from Windows-edited env
sed -i 's/\r$//' "$MQTT_ENV"
# shellcheck source=/dev/null
source "$MQTT_ENV"
set +a

[[ -n "${MOSQUITTO_USER:-}" && -n "${MOSQUITTO_PASS:-}" ]] || die "MOSQUITTO_USER/PASS required in $MQTT_ENV"
[[ "${MOSQUITTO_PASS}" != "CHANGE_ME_STRONG_SECRET" ]] || die "Replace CHANGE_ME_STRONG_SECRET in $MQTT_ENV"

DOMAIN="${PEAKLOGIC_DOMAIN:-mqtt.peaklogic.io}"
ALLOW_ANON="${MOSQUITTO_ALLOW_ANONYMOUS:-false}"

log "Configuring Mosquitto password file…"
touch /etc/mosquitto/passwd
mosquitto_passwd -b /etc/mosquitto/passwd "$MOSQUITTO_USER" "$MOSQUITTO_PASS"
# Mosquitto 2 prefers owner mosquitto; must be readable by the broker user
chown mosquitto:mosquitto /etc/mosquitto/passwd
chmod 0640 /etc/mosquitto/passwd

CONF_D=/etc/mosquitto/conf.d
install -d -m 0755 "$CONF_D"
# Mosquitto 2: auth options are global unless per_listener_settings true.
# Keep password_file / allow_anonymous once; TLS only on the 8883 listener.
# persistence* stays in /etc/mosquitto/mosquitto.conf (Debian default).
CAFILE=/etc/mosquitto/certs/server.crt
if [[ "${MOSQUITTO_TLS:-false}" == "true" ]]; then
  log "Installing MQTT TLS material for ${DOMAIN}…"
  PEAKLOGIC_DOMAIN="$DOMAIN" bash "$DEBIAN_DIR/setup-mosquitto-tls.sh"
  [[ -f /etc/mosquitto/certs/ca.crt ]] && CAFILE=/etc/mosquitto/certs/ca.crt
fi

{
  echo "# Generated by install-mqtt-droplet.sh — do not edit by hand; re-run installer"
  echo "allow_anonymous ${ALLOW_ANON}"
  echo "password_file /etc/mosquitto/passwd"
  echo
  echo "# log_dest file is set in /etc/mosquitto/mosquitto.conf (Debian default)"
  echo "log_type error"
  echo "log_type warning"
  echo "log_type notice"
  echo "log_type information"
  echo "connection_messages true"
  echo
  echo "# Opta MQTT Parc telemetry + put_program (firmware MQTT_MAX_PACKET_SIZE / MV_MQTT_CMD_BUF)"
  echo "message_size_limit 16384"
  echo
  echo "listener ${MOSQUITTO_PLAIN_PORT:-1883}"
  if [[ "${MOSQUITTO_TLS:-false}" == "true" ]]; then
    echo
    echo "listener ${MOSQUITTO_TLS_PORT:-8883}"
    echo "cafile ${CAFILE}"
    echo "certfile /etc/mosquitto/certs/server.crt"
    echo "keyfile /etc/mosquitto/certs/server.key"
    echo "require_certificate false"
  fi
} > "$CONF_D/peaklogic.conf"

# Disable default listener conflict if present
if [[ -f /etc/mosquitto/mosquitto.conf ]]; then
  sed -i 's/^\s*listener/# listener/' /etc/mosquitto/mosquitto.conf 2>/dev/null || true
fi

systemctl enable mosquitto
systemctl restart mosquitto

if command -v ufw >/dev/null 2>&1; then
  ufw allow "${MOSQUITTO_PLAIN_PORT:-1883}/tcp" comment 'MQTT' >/dev/null 2>&1 || true
  if [[ "${MOSQUITTO_TLS:-false}" == "true" ]]; then
    ufw allow "${MOSQUITTO_TLS_PORT:-8883}/tcp" comment 'MQTT TLS' >/dev/null 2>&1 || true
  fi
fi

log "Mosquitto ready"
log "  Plain: mqtt://${DOMAIN}:${MOSQUITTO_PLAIN_PORT:-1883}"
[[ "${MOSQUITTO_TLS:-false}" == "true" ]] && log "  TLS:   mqtts://${DOMAIN}:${MOSQUITTO_TLS_PORT:-8883}"
log "  Test:  mosquitto_pub -h 127.0.0.1 -p ${MOSQUITTO_PLAIN_PORT:-1883} -u $MOSQUITTO_USER -P '***' -t test/ping -m ok"
