/*
 * LilyGO T-ETH-Elite pin map (integrated A7670X).
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once
#include "sdkconfig.h"

#define BOARD_MODEM_TX_GPIO CONFIG_MODEM_UART_TX_GPIO
#define BOARD_MODEM_RX_GPIO CONFIG_MODEM_UART_RX_GPIO
#define BOARD_MODEM_PWRKEY_GPIO CONFIG_MODEM_PWRKEY_GPIO
#define BOARD_MODEM_DTR_GPIO CONFIG_MODEM_DTR_GPIO

#if CONFIG_BOARD_T_ETH_ELITE_A7670X
#define BOARD_MODEM_GPS_EN_GPIO CONFIG_MODEM_GPS_ENABLE_GPIO
#define BOARD_MODEM_GPS_EN_LEVEL CONFIG_MODEM_GPS_ENABLE_LEVEL
#define BOARD_HAS_INTEGRATED_A7670 1
#else
#define BOARD_MODEM_GPS_EN_GPIO (-1)
#define BOARD_MODEM_GPS_EN_LEVEL (0)
#define BOARD_HAS_INTEGRATED_A7670 0
#endif

#define BOARD_STATUS_LED_GPIO CONFIG_BOARD_STATUS_LED_GPIO
