/*
 * LilyGO T-ETH-Elite pin map — see LilyGo-Modem-Series utilities.h (LILYGO_T_ETH_ELITE).
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#include "sdkconfig.h"

/* W5500 Ethernet (Opta LAN) — same on integrated and stacked boards */
#define BOARD_ETH_MISO_GPIO   CONFIG_ETH_W5500_SPI_MISO
#define BOARD_ETH_MOSI_GPIO   CONFIG_ETH_W5500_SPI_MOSI
#define BOARD_ETH_SCLK_GPIO   CONFIG_ETH_W5500_SPI_SCLK
#define BOARD_ETH_CS_GPIO     CONFIG_ETH_W5500_SPI_CS
#define BOARD_ETH_INT_GPIO    CONFIG_ETH_W5500_INT_GPIO

/* A7670 modem UART */
#define BOARD_MODEM_TX_GPIO   CONFIG_MODEM_UART_TX_GPIO
#define BOARD_MODEM_RX_GPIO   CONFIG_MODEM_UART_RX_GPIO
#define BOARD_MODEM_PWRKEY_GPIO CONFIG_MODEM_PWRKEY_GPIO
#define BOARD_MODEM_DTR_GPIO  CONFIG_MODEM_DTR_GPIO

#if CONFIG_BOARD_T_ETH_ELITE_A7670X
/* Integrated T-ETH-ELITE-A7670X — GPIO4 muxes GPS vs modem UART */
#define BOARD_MODEM_GPS_EN_GPIO  CONFIG_MODEM_GPS_ENABLE_GPIO
#define BOARD_MODEM_GPS_EN_LEVEL CONFIG_MODEM_GPS_ENABLE_LEVEL
#define BOARD_HAS_INTEGRATED_A7670 1
#else
#define BOARD_MODEM_GPS_EN_GPIO  (-1)
#define BOARD_MODEM_GPS_EN_LEVEL (0)
#define BOARD_HAS_INTEGRATED_A7670 0
#endif

#define BOARD_STATUS_LED_GPIO CONFIG_BOARD_STATUS_LED_GPIO
